# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a862624378d9c4a94e8b55460a5726014b1af58ae90609f10c234a4d18fd77704db37ded5f07c36350d2dcbceaa3c5b386985808d35a5c0945fc93e4bcc2ca67

test:
  secret_key_base: 710020ee0cca83227da8bbbd5fbc1aa9b40bcb3332cfb39f6fa5eca4247dc96770ac8c2f9890199d57a55c9ec85e7666e24def4bfc7936217c8be484df2a448e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
